### ISSUE TITLE
Functionality to stop a running experiment

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#13]
We need to have a button that the user can click and stop a running experiment. 
The target system should be released and the the experiment should be marked as stopped.

**Comment by alinaciuysal** [comment]
what should be the status of experiment after user stops it? 1) Success 2) Error

**Comment by alinaciuysal** [comment]
It should be "INTERRUPTED"

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/bf64bdd6713498f9d4d5b5da6427ce08302cc338)
