### ISSUE TITLE
Showing number of stages when selecting a step size 

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#14]
When creating a new experiment in the UI (/control/experiments/create) it would be nice to show the user with the number of stages when the user updates the Step Size text field.
E.g. if
Min is set to 0
Max is set to 0.6 
and the user sets the Step Size, a message appears Next step size: "3 stages"

If Min or Max is not set, the message does not appear upon changing the Step Size text field.

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/ad1806aadefb1d37344563eb2e680ee9704322f4)
