### ISSUE TITLE
Better message when ignoring data

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#15]
We should improve the message shown when ignoring data for a stage.
Right now it is " Ignoring some of the sampled data... "

We should mention the number of stage in the above message, e.g. 
"Ignoring samples for stage X"

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/be62c57a3830a4b110fb402bd68a6913dcca136d)
