### ISSUE TITLE
Better indication of the configuration corresponding to a stage number in running exp view

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#16]
Right now, we can see which stage is running via its number, 0, 1, ... 

We need to show also the configuration that corresponds to the stage, eg. 
stage 1 --> route_random_sigma = 0
stage 2 --> route_random_sigma = 0.2
...

We need to brainstorm on the best way to do this, since it's not obvious. 
Some ideas: 
* Show the configuration in to the "experiment progress message" div
* Show the configuration in the drop-down menu of selecting a stage
* Show the mapping (similar to the example above) in the "Experiment details" by-default-hidden div

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/b728e81eb170221cf318dcffc8aa4dd472a5ca3d)

**Comment by alinaciuysal** [comment]
if we want to show configuration to the user in a drop-down for successful experiment component, we might have to add configuration values (knob values) to the elasticsearch while creating a stage tuple. otherwise, user can only see the stage configuration on-the-fly (while experiment is running).

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/df6416395a1574078576f4740a5ffb729b15d82e)
