### ISSUE TITLE
Change label of "Smooth-Line Chart" to "Scatter Plot"

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#18]
At the experiment view, the first diagram shown is labelled "Smooth-Line Chart". 
We should rename this to "Scatter Plot" since there is actually no line in this diagram :)

**Comment by alinaciuysal** [comment]
[committed here](https://github.com/Starofall/OEDA/commit/4299e4c67b2c940cb2e52c1817446437d08acea4)
