### ISSUE TITLE
Show additional plots upon experiment completion

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#19]
Right now, when an experiment is completed, we show the message "Experiment is completed with X stages..." in the "Current Status of Experiment" div. 
Also we, do not show the additional Q-Q plots at the bottom. 

The right behavior would be to remove the "Current Status of Experiment" div altogether and show the additional plots. 

The reason that this is happening is that, upon completion, we still use the "experimentRunning" API, e.g. 
<code>http://localhost:4200/control/experiments/show/937bcd6b-f0c3-ee32-e497-34bd67a9beaa/running</code>
and not the "experimentsuccess" API, e.g. 
<code>http://localhost:4200/control/experiments/show/937bcd6b-f0c3-ee32-e497-34bd67a9beaa/success</code>

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/be62c57a3830a4b110fb402bd68a6913dcca136d)
