### ISSUE TITLE
Setting up the database configuration in the UI

### ISSUE THREAD

**Issue by iliasger** [Starofall/OEDA#20]
Right now we programmatically set the necessary database configuration details in the server.py, namely the type of database, hostname and port:
<code>setup_database("elasticsearch", "localhost", 9200)</code>

It would be nice to set these in the configuration pane (which for now is empty).
I would make the above values defaults but editable in the html. 
Then, we would need to direct the user to the configuration pane if the database configuration is not set (so also when the server is fired anew). 

We should have a way to by-pass this for development purposes, because it would be impractical to setup the database every time the server restarts. 
We could consider storing this info in a cookie at the client side.

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/Starofall/OEDA/commit/6380e13e5cdd36b2fb9ac5429fa0e0a19e9a21a1)
