### ISSUE TITLE
Filtering outliers on the fly

### ISSUE THREAD

**Issue by alinaciuysal** [Starofall/OEDA#5]
Can be considered as an enhancement, because outliers affect the visualization of results

**Comment by iliasger** [comment]
This is about the scatter plot. In case of a high y value. E.g. CrowdNav "overhead" is 30, when most values are between 1 and 5, this creates a strange looking scatter plot.

**Comment by iliasger** [comment]
Actually, we need to determine what to do with the outliers in general. Apart from removing them from the diagrams on the frontend we should probably mark them as outliers in the database as well and not include them in subsequent analysis.
