### ISSUE TITLE
Notification of Remaining Stages & Estimated Time of Finish

### ISSUE THREAD

**Issue by alinaciuysal** [Starofall/OEDA#6]
User should be able to see how many stages are left while experiment is running.

**Comment by iliasger** [comment]
We can show a notification at the end of each stage.

**Comment by iliasger** [comment]
We can do everything on the client: measure the duration of each stage and calculate the estimated time to finish by multiplying the average duration of a so-far finished stage by the umber of stages and subtracting the sum of durations of so-far finished stages.

**Comment by alinaciuysal** [comment]
Instead of calculating duration of each stage at front-end, duration and remaining time are calculated at back-end and passed to oeda callback.

[implemented here](https://github.com/Starofall/OEDA/commit/cc00cdfa161c24dd874e32c4203e588093a085fe)
