### ISSUE TITLE
Continue to process an interrupted experiment

### ISSUE THREAD

**Issue by alinaciuysal** [Starofall/OEDA#7]
When target system is shut down or experiment is stopped, there is no possibility to continue the experiment afterwards.  Thus, there should be a button in UI to update status of this kind of interrupted experiment.

Buggy case: first we start running an experiment, we observe some data and plots, but stop the experiment because it would take too long. 

Then, we create another experiment that will have less number of stages. After some time, experiment is finished and labelled as "Success". When we want to see the results of previously created experiment, we still retrieve the oeda callback of the successful experiment. This occurs because the backend server does not refresh the callback dictionary until it is restarted.

**Comment by iliasger** [comment]
We generally need to make sure that callbacks are experiment-specific in order to allow for parallel handling of experiments in the frontend

**Comment by alinaciuysal** [comment]
Probably, we should make a dict of dicts in the backend, instead of only one dict
